### ISSUE TITLE
Please, add license into the composer.json

### ISSUE THREAD

**Issue by Sevavietl** [umbri/amp-react-interop#1]
First of all, thank you for the great package.

I want to try to use in my project. The problem is that we use [metasyntactical/composer-plugin-license-check](https://packagist.org/packages/metasyntactical/composer-plugin-license-check) to check packages license against the whitelist. Since the license is not in the composer.json, it fails composer install.

If you tell me what license you would like to have, I can create PR.

Thank you in advance.

**Comment by umbri** [comment]
@Sevavietl Thank you, MIT License

**Comment by Sevavietl** [comment]
Thank you for the quick response.
What year and name I should specify in the `Copyright` line of LICENCE file?

**Comment by umbri** [comment]
Oh, I think this is not important, whatever you think will be best 👍

**Comment by umbri** [comment]
#2 merged
